name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: docker build .
      - name: log in
        run: docker login --username={{ secrets.USERNAME }} --password={{ secrets.PASSWORD }}
      - name: push
        run: docker push jacfowles/dotnettemplate:tagname
   
