name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: docker build . -t jacfowles/dotnettemplate
      - name: log in
        run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
      - name: push
        run: docker push jacfowles/dotnettemplate:latest
   
